### ISSUE TITLE
Why reset encoder states?

### ISSUE THREAD

**Issue by xdwang0726** [shmpanski/transformer-summarization#1]
Hi, 

I am wondering in model.py, line 62 and 80. Why reset encoder states?
Thank you!

**Comment by shmpanski** [comment]
Hello, we cache encoder state in order to reduce calculations. You can read about in [documentation notes](https://github.com/gooppe/transformer-summarization/blob/1b23f37f238a20ef8c21ba4aeafd92401bab070e/nn/modules/transformer.py#L110).

> For optimizing model, encoder state stores in local variable and calculate it only once. Encoder state must be reseted after autoregressive decoder processing. You can do this using `Transformer.reset_encoder_state`
